# Oxe FM Synth: a software synthesizer
# Copyright (C) 2004-2026  Daniel Moura <oxesoft@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BIN_DIR:=bin
BUNDLE_NAME:=oxefmsynth.vst3
VERSION_STR:=$(shell grep '\#define VERSION_STR' src/synth/constants.h | awk -F '"' '{print $$2}')

ifeq ($(VST3SDK_PATH),)
    ifneq ($(wildcard vst3sdk/pluginterfaces/base/funknown.h),)
        VST3SDK_PATH:=vst3sdk
    else ifneq ($(wildcard .deps/vst3sdk/pluginterfaces/base/funknown.h),)
        VST3SDK_PATH:=.deps/vst3sdk
    else
        VST3SDK_PATH:=.deps/vst3sdk
    endif
endif

INCLUDES:=-Isrc/synth -Isrc/gui -Isrc/toolkits -Isrc/vst3 -I. -isystem $(VST3SDK_PATH) -I.deps/blend2d -I.deps/blend2d/blend2d -I.deps/asmjit

SOURCES:=src/synth/buffers.cpp \
         src/synth/delay.cpp \
         src/synth/envelop.cpp \
         src/synth/filter.cpp \
         src/synth/noise.cpp \
         src/synth/note.cpp \
         src/synth/oscillator.cpp \
         src/synth/persist.cpp \
         src/synth/programs.cpp \
         src/synth/reverb.cpp \
         src/synth/synthesizer.cpp \
         src/gui/button.cpp \
         src/gui/channels.cpp \
         src/gui/editor.cpp \
         src/gui/key.cpp \
         src/gui/knob.cpp \
         src/gui/lcd.cpp \
         src/gui/mapper.cpp \
         src/gui/font_data.cpp \
         src/vst3/oxevst3.cpp \
         src/vst3/oxevst3editor.cpp \
         src/vst3/vst3hostinterface.cpp \
         src/vst3/oxevst3entry.cpp \
         $(VST3SDK_PATH)/public.sdk/source/vst/vstsinglecomponenteffect.cpp \
         $(VST3SDK_PATH)/public.sdk/source/vst/vstcomponentbase.cpp \
         $(VST3SDK_PATH)/public.sdk/source/vst/vstbus.cpp \
         $(VST3SDK_PATH)/public.sdk/source/vst/vstparameters.cpp \
         $(VST3SDK_PATH)/public.sdk/source/vst/vstinitiids.cpp \
         $(VST3SDK_PATH)/public.sdk/source/main/pluginfactory.cpp \
         $(VST3SDK_PATH)/public.sdk/source/main/moduleinit.cpp \
         $(VST3SDK_PATH)/public.sdk/source/common/commoniids.cpp \
         $(VST3SDK_PATH)/public.sdk/source/common/pluginview.cpp \
         $(VST3SDK_PATH)/base/source/baseiids.cpp \
         $(VST3SDK_PATH)/base/source/fbuffer.cpp \
         $(VST3SDK_PATH)/base/source/fdebug.cpp \
         $(VST3SDK_PATH)/base/source/fobject.cpp \
         $(VST3SDK_PATH)/base/source/fstreamer.cpp \
         $(VST3SDK_PATH)/base/source/fstring.cpp \
         $(VST3SDK_PATH)/base/source/updatehandler.cpp \
         $(VST3SDK_PATH)/base/thread/source/flock.cpp \
         $(VST3SDK_PATH)/pluginterfaces/base/coreiids.cpp \
         $(VST3SDK_PATH)/pluginterfaces/base/funknown.cpp \
         $(VST3SDK_PATH)/pluginterfaces/base/ustring.cpp

CXXFLAGS+=-std=c++17 -DSMTG_RENAME_ASSERT=1 -DNDEBUG=1 -DBL_STATIC
LIBS+=-L.deps/blend2d/build -lblend2d -lpthread -lm

ifeq ($(DEBUG),YES)
    CXXFLAGS+=-g -O0
else
    CXXFLAGS+=-O3
endif

UNAME_S:=$(shell uname -s)

ifeq ($(OS),Windows_NT)
    CXX:=g++.exe
    RC:=windres.exe
    INCLUDES+=-Isrc/windows
    SOURCES+=src/toolkits/windowstoolkit.cpp \
             $(VST3SDK_PATH)/public.sdk/source/main/dllmain.cpp
    LIBS+=-lgdi32 -lole32
    LDFLAGS+=-static -s
    BUNDLE_DIR:=$(BIN_DIR)/$(BUNDLE_NAME)/Contents/x86_64-win
    BUNDLE_BINARY:=$(BUNDLE_DIR)/oxefmsynth.vst3
    BUNDLE_SETUP:=@mkdir -p $(BUNDLE_DIR)
    TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
    USER_VST3_DIR?=$(if $(LOCALAPPDATA),$(LOCALAPPDATA)/Programs/Common/VST3,$(COMMONPROGRAMFILES)/VST3)
    DEPS:=resources.o
    SOURCES+=resources.o
    INSTALL_CMD=rm -rf "$(USER_VST3_DIR)/$(BUNDLE_NAME)" && cp -R "$(TARGET_FILE)" "$(USER_VST3_DIR)/"
else
    ifeq ($(TARGET),WIN32)
        CXX:=x86_64-w64-mingw32-g++
        RC:=x86_64-w64-mingw32-windres
        INCLUDES+=-Isrc/windows
        SOURCES+=src/toolkits/windowstoolkit.cpp \
                 $(VST3SDK_PATH)/public.sdk/source/main/dllmain.cpp
        LIBS+=-lgdi32 -lole32
        LDFLAGS+=-static -s
        BUNDLE_DIR:=$(BIN_DIR)/$(BUNDLE_NAME)/Contents/x86_64-win
        BUNDLE_BINARY:=$(BUNDLE_DIR)/oxefmsynth.vst3
        BUNDLE_SETUP:=@mkdir -p $(BUNDLE_DIR)
        TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
        USER_VST3_DIR?=$(if $(LOCALAPPDATA),$(LOCALAPPDATA)/Programs/Common/VST3,$(COMMONPROGRAMFILES)/VST3)
        DEPS:=resources.o
        SOURCES+=resources.o
        INSTALL_CMD=rm -rf "$(USER_VST3_DIR)/$(BUNDLE_NAME)" && cp -R "$(TARGET_FILE)" "$(USER_VST3_DIR)/"
    else
        ifeq ($(UNAME_S),Darwin)
            ARCH_FLAGS?=-arch arm64 -arch x86_64
            CXXFLAGS+=$(ARCH_FLAGS)
            LDFLAGS+=$(ARCH_FLAGS) -framework Cocoa
            SOURCES+=src/toolkits/cocoatoolkit.mm \
                     $(VST3SDK_PATH)/public.sdk/source/main/macmain.cpp
            BUNDLE_DIR:=$(BIN_DIR)/$(BUNDLE_NAME)/Contents/MacOS
            BUNDLE_BINARY:=$(BUNDLE_DIR)/oxefmsynth
            BUNDLE_SETUP:=@mkdir -p $(BUNDLE_DIR) && cp src/macosx/vst3/PkgInfo $(BIN_DIR)/$(BUNDLE_NAME)/Contents/ 2>/dev/null || true && sed 's/__VERSION__/$(VERSION_STR)/g' src/macosx/vst3/Info.plist.in > $(BIN_DIR)/$(BUNDLE_NAME)/Contents/Info.plist
            TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
            USER_VST3_DIR?=$(HOME)/Library/Audio/Plug-Ins/VST3
            INSTALL_CMD=rm -rf "$(USER_VST3_DIR)/$(BUNDLE_NAME)" && cp -R "$(TARGET_FILE)" "$(USER_VST3_DIR)/"
        else
            SOURCES+=src/toolkits/xlibtoolkit.cpp \
                     $(VST3SDK_PATH)/public.sdk/source/main/linuxmain.cpp
            LIBS+=-lX11 -lpthread -ldl
            CXXFLAGS+=-fPIC
            LDFLAGS+=-s
            ARCH:=$(shell uname -m)
            BUNDLE_DIR:=$(BIN_DIR)/$(BUNDLE_NAME)/Contents/$(ARCH)-linux
            BUNDLE_BINARY:=$(BUNDLE_DIR)/oxefmsynth.so
            BUNDLE_SETUP:=@mkdir -p $(BUNDLE_DIR)
            TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
            USER_VST3_DIR?=$(HOME)/.vst3
            INSTALL_CMD=rm -rf "$(USER_VST3_DIR)/$(BUNDLE_NAME)" && cp -R "$(TARGET_FILE)" "$(USER_VST3_DIR)/"
        endif
    endif
endif

BLEND2D_LIB?=.deps/blend2d/build/libblend2d.a

all: $(VST3SDK_PATH)/pluginterfaces/base/funknown.h $(BLEND2D_LIB) $(DEPS)
	$(BUNDLE_SETUP)
	@$(CXX) -shared -o $(BUNDLE_BINARY) $(CXXFLAGS) $(SOURCES) $(INCLUDES) $(LIBS) $(LDFLAGS)

install:
	@if [ -d "$(TARGET_FILE)" ] && [ -f "$(BUNDLE_BINARY)" ]; then \
		echo "Installing $(TARGET_FILE) to $(USER_VST3_DIR)"; \
		mkdir -p "$(USER_VST3_DIR)"; \
		$(INSTALL_CMD); \
	else \
		echo "$(TARGET_FILE) is not built. Build it first with 'make vst3' (or 'make -f Makefile.vst3')."; \
	fi

$(VST3SDK_PATH)/pluginterfaces/base/funknown.h:
	@echo "Downloading VST3 SDK..."
	@mkdir -p .deps
	@git clone --depth 1 --branch v3.7.14_build_55 https://github.com/steinbergmedia/vst3sdk.git .deps/vst3sdk
	@cd .deps/vst3sdk && git submodule update --init --depth 1 base cmake pluginterfaces public.sdk

ifeq ($(UNAME_S),Darwin)
$(BLEND2D_LIB):
	@echo "Downloading and building Blend2D (Universal)..."
	@mkdir -p .deps
	@if [ ! -d .deps/asmjit ]; then git clone --depth 1 https://github.com/asmjit/asmjit.git .deps/asmjit; fi
	@if [ ! -d .deps/blend2d ]; then git clone --depth 1 https://github.com/blend2d/blend2d.git .deps/blend2d; fi
	@cmake -B .deps/blend2d/build_arm64 -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_OSX_ARCHITECTURES=arm64
	@cmake --build .deps/blend2d/build_arm64 --config Release
	@cmake -B .deps/blend2d/build_x86_64 -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_OSX_ARCHITECTURES=x86_64
	@cmake --build .deps/blend2d/build_x86_64 --config Release
	@mkdir -p .deps/blend2d/build
	@lipo -create .deps/blend2d/build_arm64/libblend2d.a .deps/blend2d/build_x86_64/libblend2d.a -output .deps/blend2d/build/libblend2d.a
else
$(BLEND2D_LIB):
	@echo "Downloading and building Blend2D..."
	@mkdir -p .deps
	@if [ ! -d .deps/asmjit ]; then git clone --depth 1 https://github.com/asmjit/asmjit.git .deps/asmjit; fi
	@if [ ! -d .deps/blend2d ]; then git clone --depth 1 https://github.com/blend2d/blend2d.git .deps/blend2d; fi
	@cmake -B .deps/blend2d/build -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_POSITION_INDEPENDENT_CODE=ON
	@cmake --build .deps/blend2d/build --config Release
endif

resources.o:
	@$(RC) -Isrc/synth -Isrc/windows src/windows/resources.rc resources.o

clean:
	@rm -rf $(TARGET_FILE) $(BUNDLE_NAME) *.o *.d

.PHONY: all clean install

