# Oxe FM Synth: a software synthesizer
# Copyright (C) 2015  Daniel Moura <oxe@oxesoft.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

EXECUTABLE_NAME:=oxefmsynth
VERSION_STR:=$(shell grep '\#define VERSION_STR' src/synth/constants.h | awk -F '"' '{print $$2}')

INCLUDES+=-Isrc/gui
INCLUDES+=-Isrc/synth
INCLUDES+=-Isrc/toolkits
INCLUDES+=-I.deps/blend2d -I.deps/blend2d/blend2d -I.deps/asmjit

CXXFLAGS+=-std=c++17 -DBL_STATIC
LDFLAGS+=-L.deps/blend2d/build -lblend2d -lpthread -lm

SOURCES+=src/toolkits/nonguitoolkit.cpp
SOURCES+=src/standalone/main.cpp
SOURCES+=src/gui/button.cpp
SOURCES+=src/gui/channels.cpp
SOURCES+=src/gui/editor.cpp
SOURCES+=src/gui/key.cpp
SOURCES+=src/gui/knob.cpp
SOURCES+=src/gui/lcd.cpp
SOURCES+=src/gui/mapper.cpp
SOURCES+=src/synth/buffers.cpp
SOURCES+=src/synth/delay.cpp
SOURCES+=src/synth/envelop.cpp
SOURCES+=src/synth/filter.cpp
SOURCES+=src/synth/noise.cpp
SOURCES+=src/synth/note.cpp
SOURCES+=src/synth/oscillator.cpp
SOURCES+=src/synth/persist.cpp
SOURCES+=src/synth/programs.cpp
SOURCES+=src/synth/reverb.cpp
SOURCES+=src/synth/synthesizer.cpp

UNAME_S:=$(shell uname -s)

ifeq ($(DEBUG),YES)
    CXXFLAGS+=-g -O0
else
    CXXFLAGS+=-O3
    ifneq ($(UNAME_S),Darwin)
        LDFLAGS+=-s
    endif
endif

ifeq ($(OS),Windows_NT)
    EXECUTABLE_NAME:=$(EXECUTABLE_NAME).exe
    CXX:=g++.exe
    RC:=windres.exe
    INCLUDES+=-Isrc/standalone
    SOURCES+=src/toolkits/windowstoolkit.cpp
    INCLUDES+=-Isrc/windows
    LDFLAGS+=-lgdi32
    LDFLAGS+=resources.o
    DEPS:=resources.o
else
    ifeq ($(TARGET),WIN32)
        EXECUTABLE_NAME:=$(EXECUTABLE_NAME).exe
        CXX:=i686-w64-mingw32-g++
        RC:=i686-w64-mingw32-windres
        INCLUDES+=-Isrc/standalone
        SOURCES+=src/toolkits/windowstoolkit.cpp
        INCLUDES+=-Isrc/windows
        LDFLAGS+=-lgdi32
        LDFLAGS+=resources.o
        DEPS:=resources.o
        LDFLAGS+=-static
    else
        INCLUDES+=-I.
        ifeq ($(UNAME_S),Darwin)
            LDFLAGS+=-framework Cocoa
            SOURCES+=src/toolkits/cocoatoolkit.mm
        else
            LDFLAGS+=-lX11
            LDFLAGS+=-lpthread
            LDFLAGS+=-ldl
            SOURCES+=src/toolkits/xlibtoolkit.cpp
        endif
    endif
endif

all: $(DEPS)
	@$(CXX) -o $(EXECUTABLE_NAME) -DEXECUTABLE_NAME=\"$(EXECUTABLE_NAME)\" $(CXXFLAGS) $(SOURCES) $(INCLUDES) $(LDFLAGS)
	@$(CMD)
ifeq ($(UNAME_S),Darwin)
	@mkdir -p $(EXECUTABLE_NAME).app/Contents/MacOS
	@cp src/macosx/app/PkgInfo $(EXECUTABLE_NAME).app/Contents/ 2>/dev/null || true
	@sed 's/__VERSION__/$(VERSION_STR)/g' src/macosx/app/Info.plist.in > $(EXECUTABLE_NAME).app/Contents/Info.plist
	@mv $(EXECUTABLE_NAME) $(EXECUTABLE_NAME).app/Contents/MacOS/
endif

resources.o:
	@$(RC) -Isrc/synth src/windows/resources.rc resources.o

clean:
	@rm -rf $(EXECUTABLE_NAME).app $(EXECUTABLE_NAME) *.o *.d
