# Oxe FM Synth: a software synthesizer
# Copyright (C) 2004-2026  Daniel Moura <oxesoft@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BIN_DIR:=bin
BUNDLE_NAME:=oxefmsynth.clap
VERSION_STR:=$(shell grep '\#define VERSION_STR' src/synth/constants.h | awk -F '"' '{print $$2}')

ifeq ($(CLAPSDK_PATH),)
    ifneq ($(wildcard clap/include/clap/clap.h),)
        CLAPSDK_PATH:=clap
    else ifneq ($(wildcard .deps/clap/include/clap/clap.h),)
        CLAPSDK_PATH:=.deps/clap
    else
        CLAPSDK_PATH:=.deps/clap
    endif
endif

INCLUDES:=-Isrc/synth -Isrc/gui -Isrc/toolkits -Isrc/clap -I. -isystem $(CLAPSDK_PATH)/include -I.deps/blend2d -I.deps/blend2d/blend2d -I.deps/asmjit

SOURCES:=src/synth/buffers.cpp \
         src/synth/delay.cpp \
         src/synth/envelop.cpp \
         src/synth/filter.cpp \
         src/synth/noise.cpp \
         src/synth/note.cpp \
         src/synth/oscillator.cpp \
         src/synth/persist.cpp \
         src/synth/programs.cpp \
         src/synth/reverb.cpp \
         src/synth/synthesizer.cpp \
         src/gui/button.cpp \
         src/gui/channels.cpp \
         src/gui/editor.cpp \
         src/gui/key.cpp \
         src/gui/knob.cpp \
         src/gui/lcd.cpp \
         src/gui/mapper.cpp \
         src/gui/font_data.cpp \
         src/clap/oxeclap.cpp \
         src/clap/oxeclapentry.cpp \
         src/clap/claphostinterface.cpp

CXXFLAGS+=-std=c++17 -DBL_STATIC
LIBS+=-L.deps/blend2d/build -lblend2d -lpthread -lm

ifeq ($(DEBUG),YES)
    CXXFLAGS+=-g -O0
else
    CXXFLAGS+=-O3
endif

UNAME_S:=$(shell uname -s)

ifeq ($(OS),Windows_NT)
    CXX:=g++.exe
    RC:=windres.exe
    INCLUDES+=-Isrc/windows
    SOURCES+=src/toolkits/windowstoolkit.cpp
    LIBS+=-lgdi32
    LDFLAGS+=-static -s
    TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
    BUNDLE_BINARY:=$(TARGET_FILE)
    BUNDLE_SETUP:=@mkdir -p $(BIN_DIR)
    USER_CLAP_DIR?=$(if $(LOCALAPPDATA),$(LOCALAPPDATA)/Programs/Common/CLAP,$(COMMONPROGRAMFILES)/CLAP)
    DEPS:=resources.o
    SOURCES+=resources.o
    INSTALL_CMD=cp -f "$(TARGET_FILE)" "$(USER_CLAP_DIR)/"
else
    ifeq ($(TARGET),WIN32)
        CXX:=x86_64-w64-mingw32-g++
        RC:=x86_64-w64-mingw32-windres
        INCLUDES+=-Isrc/windows
        SOURCES+=src/toolkits/windowstoolkit.cpp
        LIBS+=-lgdi32
        LDFLAGS+=-static -s
        TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
        BUNDLE_BINARY:=$(TARGET_FILE)
        BUNDLE_SETUP:=@mkdir -p $(BIN_DIR)
        USER_CLAP_DIR?=$(if $(LOCALAPPDATA),$(LOCALAPPDATA)/Programs/Common/CLAP,$(COMMONPROGRAMFILES)/CLAP)
        DEPS:=resources.o
        SOURCES+=resources.o
        INSTALL_CMD=cp -f "$(TARGET_FILE)" "$(USER_CLAP_DIR)/"
    else
        ifeq ($(UNAME_S),Darwin)
            ARCH_FLAGS?=-arch arm64 -arch x86_64
            CXXFLAGS+=$(ARCH_FLAGS)
            LDFLAGS+=$(ARCH_FLAGS) -framework Cocoa
            SOURCES+=src/toolkits/cocoatoolkit.mm
            BUNDLE_DIR:=$(BIN_DIR)/$(BUNDLE_NAME)/Contents/MacOS
            BUNDLE_BINARY:=$(BUNDLE_DIR)/oxefmsynth
            BUNDLE_SETUP:=@mkdir -p $(BUNDLE_DIR) && cp src/macosx/clap/PkgInfo $(BIN_DIR)/$(BUNDLE_NAME)/Contents/ 2>/dev/null || true && sed 's/__VERSION__/$(VERSION_STR)/g' src/macosx/clap/Info.plist.in > $(BIN_DIR)/$(BUNDLE_NAME)/Contents/Info.plist
            TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
            USER_CLAP_DIR?=$(HOME)/Library/Audio/Plug-Ins/CLAP
            INSTALL_CMD=rm -rf "$(USER_CLAP_DIR)/$(BUNDLE_NAME)" && cp -R "$(TARGET_FILE)" "$(USER_CLAP_DIR)/"
        else
            LIBS+=-lX11 -lpthread -ldl
            CXXFLAGS+=-fPIC
            LDFLAGS+=-s
            SOURCES+=src/toolkits/xlibtoolkit.cpp
            TARGET_FILE:=$(BIN_DIR)/$(BUNDLE_NAME)
            BUNDLE_BINARY:=$(TARGET_FILE)
            BUNDLE_SETUP:=@mkdir -p $(BIN_DIR)
            USER_CLAP_DIR?=$(HOME)/.clap
            INSTALL_CMD=cp -f "$(TARGET_FILE)" "$(USER_CLAP_DIR)/"
        endif
    endif
endif

BLEND2D_LIB?=.deps/blend2d/build/libblend2d.a

all: $(CLAPSDK_PATH)/include/clap/clap.h $(BLEND2D_LIB) $(DEPS)
	$(BUNDLE_SETUP)
	@$(CXX) -shared -o $(BUNDLE_BINARY) $(CXXFLAGS) $(SOURCES) $(INCLUDES) $(LIBS) $(LDFLAGS)

install:
	@if [ -e "$(BUNDLE_BINARY)" ]; then \
		echo "Installing $(TARGET_FILE) to $(USER_CLAP_DIR)"; \
		mkdir -p "$(USER_CLAP_DIR)"; \
		$(INSTALL_CMD); \
	else \
		echo "$(TARGET_FILE) is not built. Build it first with 'make clap' (or 'make -f Makefile.clap')."; \
	fi

$(CLAPSDK_PATH)/include/clap/clap.h:
	@echo "Downloading CLAP SDK..."
	@mkdir -p .deps
	@git clone --depth 1 --branch 1.2.10 https://github.com/free-audio/clap.git .deps/clap

ifeq ($(UNAME_S),Darwin)
$(BLEND2D_LIB):
	@echo "Downloading and building Blend2D (Universal)..."
	@mkdir -p .deps
	@if [ ! -d .deps/asmjit ]; then git clone --depth 1 https://github.com/asmjit/asmjit.git .deps/asmjit; fi
	@if [ ! -d .deps/blend2d ]; then git clone --depth 1 https://github.com/blend2d/blend2d.git .deps/blend2d; fi
	@cmake -B .deps/blend2d/build_arm64 -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_OSX_ARCHITECTURES=arm64
	@cmake --build .deps/blend2d/build_arm64 --config Release
	@cmake -B .deps/blend2d/build_x86_64 -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_OSX_ARCHITECTURES=x86_64
	@cmake --build .deps/blend2d/build_x86_64 --config Release
	@mkdir -p .deps/blend2d/build
	@lipo -create .deps/blend2d/build_arm64/libblend2d.a .deps/blend2d/build_x86_64/libblend2d.a -output .deps/blend2d/build/libblend2d.a
else
$(BLEND2D_LIB):
	@echo "Downloading and building Blend2D..."
	@mkdir -p .deps
	@if [ ! -d .deps/asmjit ]; then git clone --depth 1 https://github.com/asmjit/asmjit.git .deps/asmjit; fi
	@if [ ! -d .deps/blend2d ]; then git clone --depth 1 https://github.com/blend2d/blend2d.git .deps/blend2d; fi
	@cmake -B .deps/blend2d/build -S .deps/blend2d -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DCMAKE_POSITION_INDEPENDENT_CODE=ON
	@cmake --build .deps/blend2d/build --config Release
endif

resources.o:
	@$(RC) -Isrc/synth -Isrc/windows src/windows/resources.rc resources.o

clean:
	@rm -rf $(TARGET_FILE) $(BUNDLE_NAME) *.o *.d

.PHONY: all clean install
